server:
  port: 8891
spring:
  application:
    name: lstp-zstp-todb-service
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        namespace: 4a11c94f-d36f-4a3d-86f4-d0bf359f9dab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: linsz99@
    username: root
    url: jdbc:mysql//localhost:3306?lstp&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC


feign:
  httpclient:
    connection-timeout: 60000
    max-connections: 20000


#knife4j:
#  enable: true
#  openapi:
#    title: lstp-zstp-todb-service-接口
#    description: "lstp-zstp-todb-知识图谱模块接口"
#    email: xiaoymin@foxmail.com
#    concat: 八一菜刀
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      todb:
#        group-name: todb-知识图谱-人物模块
#        api-rule: package
#        api-rule-resources:
#          - com.lin.todb.renwu.controller
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
